// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class SFTPDirectory {
    "path": string;
    "entries": SFTPEntry[];

    /** Creates a new SFTPDirectory instance. */
    constructor($$source: Partial<SFTPDirectory> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SFTPDirectory instance from a string or object.
     */
    static createFrom($$source: any = {}): SFTPDirectory {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField1_0($$parsedSource["entries"]);
        }
        return new SFTPDirectory($$parsedSource as Partial<SFTPDirectory>);
    }
}

export class SFTPEntry {
    "name": string;
    "path": string;
    "isDir": boolean;
    "size": number;
    "modTime": number;
    "mode": string;

    /** Creates a new SFTPEntry instance. */
    constructor($$source: Partial<SFTPEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("modTime" in $$source)) {
            this["modTime"] = 0;
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SFTPEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): SFTPEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SFTPEntry($$parsedSource as Partial<SFTPEntry>);
    }
}

export class SSHConnectionConfig {
    "id": string;
    "host": string;
    "port": number;
    "username": string;
    "password"?: string;
    "privateKey"?: string;
    "privateKeyPassphrase"?: string;
    "jumpHost"?: SSHJumpHostConfig | null;
    "jumpHosts"?: SSHJumpHostConfig[];
    "portForwards"?: SSHPortForward[];

    /** Creates a new SSHConnectionConfig instance. */
    constructor($$source: Partial<SSHConnectionConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHConnectionConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHConnectionConfig {
        const $$createField7_0 = $$createType3;
        const $$createField8_0 = $$createType4;
        const $$createField9_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("jumpHost" in $$parsedSource) {
            $$parsedSource["jumpHost"] = $$createField7_0($$parsedSource["jumpHost"]);
        }
        if ("jumpHosts" in $$parsedSource) {
            $$parsedSource["jumpHosts"] = $$createField8_0($$parsedSource["jumpHosts"]);
        }
        if ("portForwards" in $$parsedSource) {
            $$parsedSource["portForwards"] = $$createField9_0($$parsedSource["portForwards"]);
        }
        return new SSHConnectionConfig($$parsedSource as Partial<SSHConnectionConfig>);
    }
}

export class SSHJumpHostConfig {
    "host": string;
    "port": number;
    "username": string;
    "password"?: string;
    "privateKey"?: string;
    "privateKeyPassphrase"?: string;

    /** Creates a new SSHJumpHostConfig instance. */
    constructor($$source: Partial<SSHJumpHostConfig> = {}) {
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHJumpHostConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHJumpHostConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHJumpHostConfig($$parsedSource as Partial<SSHJumpHostConfig>);
    }
}

export class SSHPortForward {
    "mode": string;
    "listenAddress": string;
    "listenPort": number;
    "targetAddress": string;
    "targetPort": number;

    /** Creates a new SSHPortForward instance. */
    constructor($$source: Partial<SSHPortForward> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("listenAddress" in $$source)) {
            this["listenAddress"] = "";
        }
        if (!("listenPort" in $$source)) {
            this["listenPort"] = 0;
        }
        if (!("targetAddress" in $$source)) {
            this["targetAddress"] = "";
        }
        if (!("targetPort" in $$source)) {
            this["targetPort"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHPortForward instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHPortForward {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHPortForward($$parsedSource as Partial<SSHPortForward>);
    }
}

// Private type creation functions
const $$createType0 = SFTPEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = SSHJumpHostConfig.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType2);
const $$createType5 = SSHPortForward.createFrom;
const $$createType6 = $Create.Array($$createType5);
