// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Connect(config: $models.SSHConnectionConfig | null): $CancellablePromise<void> {
    return $Call.ByID(662660765, config);
}

export function Disconnect(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2124563103, sessionID);
}

export function DownloadSFTPFile(sessionID: string, remotePath: string, suggestedFilename: string, dialogTitle: string): $CancellablePromise<boolean> {
    return $Call.ByID(3804303342, sessionID, remotePath, suggestedFilename, dialogTitle);
}

/**
 * Input writes data to SSH stdin
 */
export function Input(sessionID: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(187872847, sessionID, data);
}

export function ListSFTPDirectory(sessionID: string, directory: string): $CancellablePromise<$models.SFTPDirectory> {
    return $Call.ByID(2185363387, sessionID, directory).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Resize(sessionID: string, rows: number, cols: number): $CancellablePromise<void> {
    return $Call.ByID(639676773, sessionID, rows, cols);
}

export function UploadSFTPFile(sessionID: string, remotePath: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(2800851959, sessionID, remotePath, data);
}

// Private type creation functions
const $$createType0 = $models.SFTPDirectory.createFrom;
