// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function Authenticate(): $CancellablePromise<void> {
    return $Call.ByID(1674331858);
}

export function StartAutoSync(): $CancellablePromise<void> {
    return $Call.ByID(1648096369);
}

export function StopAutoSync(): $CancellablePromise<void> {
    return $Call.ByID(2958838027);
}

export function Sync(): $CancellablePromise<void> {
    return $Call.ByID(3951821300);
}
