// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class SSHClosedPayload {
    "id": string;

    /** Creates a new SSHClosedPayload instance. */
    constructor($$source: Partial<SSHClosedPayload> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHClosedPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHClosedPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHClosedPayload($$parsedSource as Partial<SSHClosedPayload>);
    }
}

export class SSHDataPayload {
    "id": string;
    "data": string;

    /** Creates a new SSHDataPayload instance. */
    constructor($$source: Partial<SSHDataPayload> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHDataPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHDataPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHDataPayload($$parsedSource as Partial<SSHDataPayload>);
    }
}

export class SSHMetricsPayload {
    "id": string;
    "cpu": number;
    "ioWait": number;
    /** Load average over 1, 5 and 15 minutes, as reported by /proc/loadavg. */
    "load1": number;
    "load5": number;
    "load15": number;
    "memory": number;
    "swap": number;
    "disk": number;
    /** Bytes per second, summed over every interface but the loopback. */
    "networkIn": number;
    "networkOut": number;
    /** Uptime in seconds. */
    "uptime": number;
    "processesRunning": number;
    "processesTotal": number;

    /** Creates a new SSHMetricsPayload instance. */
    constructor($$source: Partial<SSHMetricsPayload> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("cpu" in $$source)) {
            this["cpu"] = 0;
        }
        if (!("ioWait" in $$source)) {
            this["ioWait"] = 0;
        }
        if (!("load1" in $$source)) {
            this["load1"] = 0;
        }
        if (!("load5" in $$source)) {
            this["load5"] = 0;
        }
        if (!("load15" in $$source)) {
            this["load15"] = 0;
        }
        if (!("memory" in $$source)) {
            this["memory"] = 0;
        }
        if (!("swap" in $$source)) {
            this["swap"] = 0;
        }
        if (!("disk" in $$source)) {
            this["disk"] = 0;
        }
        if (!("networkIn" in $$source)) {
            this["networkIn"] = 0;
        }
        if (!("networkOut" in $$source)) {
            this["networkOut"] = 0;
        }
        if (!("uptime" in $$source)) {
            this["uptime"] = 0;
        }
        if (!("processesRunning" in $$source)) {
            this["processesRunning"] = 0;
        }
        if (!("processesTotal" in $$source)) {
            this["processesTotal"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHMetricsPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHMetricsPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHMetricsPayload($$parsedSource as Partial<SSHMetricsPayload>);
    }
}

export class UpdaterProgressPayload {
    "downloaded": number;
    "total": number;
    "percent": number;

    /** Creates a new UpdaterProgressPayload instance. */
    constructor($$source: Partial<UpdaterProgressPayload> = {}) {
        if (!("downloaded" in $$source)) {
            this["downloaded"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("percent" in $$source)) {
            this["percent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdaterProgressPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdaterProgressPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdaterProgressPayload($$parsedSource as Partial<UpdaterProgressPayload>);
    }
}

export class SFTPProgressPayload {
    "id": string;
    "direction": string;
    "name": string;
    "path": string;
    "transferred": number;
    "total": number;

    /** Creates a new SFTPProgressPayload instance. */
    constructor($$source: Partial<SFTPProgressPayload> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("direction" in $$source)) {
            this["direction"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("transferred" in $$source)) {
            this["transferred"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SFTPProgressPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): SFTPProgressPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SFTPProgressPayload($$parsedSource as Partial<SFTPProgressPayload>);
    }
}
