// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppSettings {
    "language": string;
    "showHostGroups": boolean;
    "hostViewMode": string;
    "groupViewMode": string;
    "vaultDirectory": string;
    "pendingVaultDirectory"?: string;
    "pendingVaultAction"?: string;

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("showHostGroups" in $$source)) {
            this["showHostGroups"] = false;
        }
        if (!("hostViewMode" in $$source)) {
            this["hostViewMode"] = "";
        }
        if (!("groupViewMode" in $$source)) {
            this["groupViewMode"] = "";
        }
        if (!("vaultDirectory" in $$source)) {
            this["vaultDirectory"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}
