// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(1855091376).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * MoveVaultToDirectory schedules an offline database move and restarts the app.
 */
export function MoveVaultToDirectory(directory: string): $CancellablePromise<void> {
    return $Call.ByID(3831032522, directory);
}

export function SaveSettings(settings: $models.AppSettings): $CancellablePromise<void> {
    return $Call.ByID(532647211, settings);
}

export function SelectVaultDirectory(): $CancellablePromise<string> {
    return $Call.ByID(516025752);
}

/**
 * SwitchVaultDirectory activates another vault directory without moving the current database.
 */
export function SwitchVaultDirectory(directory: string): $CancellablePromise<void> {
    return $Call.ByID(3069812536, directory);
}

// Private type creation functions
const $$createType0 = $models.AppSettings.createFrom;
