// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetCurrentUser(): $CancellablePromise<$models.UserInfo | null> {
    return $Call.ByID(1916381211).then(($result: any) => {
        return $$createType1($result);
    });
}

export function HasUser(): $CancellablePromise<boolean> {
    return $Call.ByID(3611316560);
}

export function LockVault(): $CancellablePromise<void> {
    return $Call.ByID(556686206);
}

/**
 * Login - "unlock vault"
 */
export function Login(password: string): $CancellablePromise<void> {
    return $Call.ByID(3201915010, password);
}

/**
 * LoginFromSync - "connect and restore"
 */
export function LoginFromSync(serverUrl: string, username: string, password: string): $CancellablePromise<void> {
    return $Call.ByID(160253189, serverUrl, username, password);
}

export function RegisterLocal(username: string, password: string): $CancellablePromise<void> {
    return $Call.ByID(3138330411, username, password);
}

export function RegisterOnServer(serverURL: string): $CancellablePromise<void> {
    return $Call.ByID(2751812862, serverURL);
}

export function WipeData(): $CancellablePromise<void> {
    return $Call.ByID(2979742198);
}

// Private type creation functions
const $$createType0 = $models.UserInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
