// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppSettings {
    "language": string;
    "showHostGroups": boolean;
    "showSidebarToggle": boolean;
    "serverMetrics": boolean;
    "hostViewMode": string;
    "groupViewMode": string;
    "appBackgroundColor"?: string;
    "appForegroundColor"?: string;
    "appAccentColor"?: string;
    "appFontFamily"?: string;
    "terminalBackground"?: string;
    "terminalForeground"?: string;
    "terminalCursor"?: string;
    "terminalCursorStyle"?: string;
    "terminalFontFamily"?: string;
    "terminalFontSize"?: number;
    "splitPaneBorder"?: string;
    "splitPaneHeaderColor"?: string;
    "serverMetricsColor"?: string;
    "sidebarColor"?: string;
    "inputColor"?: string;
    "ringColor"?: string;
    "savedPalettes"?: ColorPalette[];
    "groupViewModeVersion"?: number;
    "vaultDirectory": string;
    "pendingVaultDirectory"?: string;
    "pendingVaultAction"?: string;

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("showHostGroups" in $$source)) {
            this["showHostGroups"] = false;
        }
        if (!("showSidebarToggle" in $$source)) {
            this["showSidebarToggle"] = false;
        }
        if (!("serverMetrics" in $$source)) {
            this["serverMetrics"] = false;
        }
        if (!("hostViewMode" in $$source)) {
            this["hostViewMode"] = "";
        }
        if (!("groupViewMode" in $$source)) {
            this["groupViewMode"] = "";
        }
        if (!("vaultDirectory" in $$source)) {
            this["vaultDirectory"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}

export class ColorPalette {
    "name": string;
    "appBackgroundColor": string;
    "appForegroundColor": string;
    "appAccentColor": string;
    "terminalBackgroundColor": string;
    "terminalForegroundColor": string;
    "terminalCursorColor": string;

    /** Creates a new ColorPalette instance. */
    constructor($$source: Partial<ColorPalette> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("appBackgroundColor" in $$source)) {
            this["appBackgroundColor"] = "";
        }
        if (!("appForegroundColor" in $$source)) {
            this["appForegroundColor"] = "";
        }
        if (!("appAccentColor" in $$source)) {
            this["appAccentColor"] = "";
        }
        if (!("terminalBackgroundColor" in $$source)) {
            this["terminalBackgroundColor"] = "";
        }
        if (!("terminalForegroundColor" in $$source)) {
            this["terminalForegroundColor"] = "";
        }
        if (!("terminalCursorColor" in $$source)) {
            this["terminalCursorColor"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColorPalette instance from a string or object.
     */
    static createFrom($$source: any = {}): ColorPalette {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColorPalette($$parsedSource as Partial<ColorPalette>);
    }
}
