// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(4218943428).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * MoveVaultToDirectory schedules an offline database move and restarts the app.
 */
export function MoveVaultToDirectory(directory: string): $CancellablePromise<void> {
    return $Call.ByID(2296513222, directory);
}

export function SaveSettings(settings: $models.AppSettings): $CancellablePromise<void> {
    return $Call.ByID(1201925327, settings);
}

export function SelectVaultDirectory(): $CancellablePromise<string> {
    return $Call.ByID(666012212);
}

/**
 * SwitchVaultDirectory activates another vault directory without moving the current database.
 */
export function SwitchVaultDirectory(directory: string): $CancellablePromise<void> {
    return $Call.ByID(1023366692, directory);
}

// Private type creation functions
const $$createType0 = $models.AppSettings.createFrom;
